# Generated by Django 4.0.6 on 2022-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False, verbose_name='좋아요'),
        ),
    ]
