# Generated by Django 4.0.6 on 2022-07-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('type', models.CharField(max_length=50, verbose_name='종류')),
                ('description', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%y%m%d', verbose_name='이미지')),
                ('description', models.TextField(verbose_name='설명')),
                ('interest', models.IntegerField(verbose_name='관심도')),
                ('tool', models.CharField(choices=[], max_length=50)),
                ('tool_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ideas.tool')),
            ],
        ),
    ]
