# Generated by Django 4.0.6 on 2022-07-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='tool',
        ),
    ]
