# Generated by Django 4.0.6 on 2022-07-19 17:37

from django.db import migrations

def fill_tool_fk(apps, schema_editor):
    Idea = apps.get_model('ideas','Idea')
    Tool = apps.get_model('ideas', 'Tool')
    for idea in Idea.objects.all():
        idea.tool_fk, created = Tool.objects.get_or_create(name=Idea.tool)
        idea.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_tool_fk),
    ]
