# Generated by Django 4.0.6 on 2022-07-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20220720_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='tool',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='tool_fk',
            new_name='tool',
        ),
    ]
