# Generated by Django 4.0.6 on 2022-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_test_idea_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
