# Generated by Django 4.0.6 on 2022-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_idea_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tool',
            field=models.CharField(choices=[(None, '------'), ('Django', 'Django'), ('Python', 'Python')], max_length=50, null=True, verbose_name='개발툴'),
        ),
    ]
