# Generated by Django 4.0.6 on 2022-07-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_idea_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_tool', to='ideas.tool'),
        ),
    ]
