# Generated by Django 4.0.6 on 2022-07-20 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_remove_idea_likes_idea_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
