# Generated by Django 4.0.6 on 2022-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('release_year', models.CharField(max_length=4, verbose_name='개봉년도')),
                ('genre', models.CharField(choices=[('ACTION', '액션'), ('CRIME', '범죄'), ('SF', 'SF'), ('COMEDY', '코미디'), ('ROMANCE', '로맨스'), ('ROMANCE-COMEDY', '로맨스 코미디'), ('BLACK-COMEDY', '블랙 코미디'), ('THRILLER', '스릴러'), ('HORROR', '공포'), ('WAR', '전쟁'), ('FANTASY', '판타지'), ('MUSIC', '음악'), ('HISTORICAL', '역사'), ('DRAMA', '드라마'), ('DOCUMENTARY', '다큐멘터리')], max_length=14, verbose_name='장르')),
                ('star', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='별점')),
                ('runtime', models.IntegerField(verbose_name='러닝타임')),
                ('review', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actor', models.CharField(max_length=50, verbose_name='배우')),
            ],
        ),
    ]
