# Generated by Django 4.0.6 on 2022-07-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='release_year',
            new_name='year',
        ),
    ]
